name: ecom_app
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.0
  firebase_analytics: ^11.3.5
  firebase_crashlytics: ^4.1.5
  firebase_auth:
  cloud_firestore:
  flutter_svg:
  flutter_bloc:
  dartz:
  get_it:

dev_dependencies:
  flutter_test:
    sdk: flutter

android:
  minSdkVersion: 23
flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/vectors/
    # - assets/images/

  fonts:
    - family: CircularStd
      fonts:
        - asset: assets/fonts/CircularStd-Black.ttf
          weight: 800
        - asset: assets/fonts/CircularStd-Bold.ttf
          weight: 700
        - asset: assets/fonts/CircularStd-Medium.ttf
          weight: 500
        - asset: assets/fonts/CircularStd-Regular.ttf
          weight: 400
