// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyyoHNEFdmY7yXujBMUrYIXLyiYgz7m2o',
    appId: '1:306528987998:web:440c94b76771898e193dcf',
    messagingSenderId: '306528987998',
    projectId: 'ecom-app-bbc91',
    authDomain: 'ecom-app-bbc91.firebaseapp.com',
    storageBucket: 'ecom-app-bbc91.firebasestorage.app',
    measurementId: 'G-YY9SGEM5HE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2adk-ZRkGdbNVOronOoUNXvOt7jhOECE',
    appId: '1:306528987998:android:63c891434f802baf193dcf',
    messagingSenderId: '306528987998',
    projectId: 'ecom-app-bbc91',
    storageBucket: 'ecom-app-bbc91.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5AIK7JsIYhk7I75wFl50jGklUgtup6Uw',
    appId: '1:306528987998:ios:db2d8028ed7a12d1193dcf',
    messagingSenderId: '306528987998',
    projectId: 'ecom-app-bbc91',
    storageBucket: 'ecom-app-bbc91.firebasestorage.app',
    iosBundleId: 'com.example.ecomApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5AIK7JsIYhk7I75wFl50jGklUgtup6Uw',
    appId: '1:306528987998:ios:db2d8028ed7a12d1193dcf',
    messagingSenderId: '306528987998',
    projectId: 'ecom-app-bbc91',
    storageBucket: 'ecom-app-bbc91.firebasestorage.app',
    iosBundleId: 'com.example.ecomApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyyoHNEFdmY7yXujBMUrYIXLyiYgz7m2o',
    appId: '1:306528987998:web:fbea3e0f20e674af193dcf',
    messagingSenderId: '306528987998',
    projectId: 'ecom-app-bbc91',
    authDomain: 'ecom-app-bbc91.firebaseapp.com',
    storageBucket: 'ecom-app-bbc91.firebasestorage.app',
    measurementId: 'G-KS49V1G6K2',
  );
}
